# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
- repo: https://github.com/psf/black-pre-commit-mirror
  rev: 24.4.2
  hooks:
  - id: black
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff's latest tag contains a pre-built wheel for the hook.
  # The rev is auto-updated by the pre-commit bot.
  rev: v0.5.2
  hooks:
    - id: ruff
    - id: ruff-format
